name: Process Data
on:
  push:
    paths:
      - 'main.js'
      - 'config.js'
  schedule:
    - cron: '*/5 23 * * *'
    - cron: '*/5 0-6 * * *'
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm i

      - name: Process
        run: npm start
        env:
          TOKEN: ${{ secrets.TOKEN }}
          COOKIE: ${{ secrets.COOKIE }}
          KEY: ${{ secrets.KEY }}

      - name: Push data
        run: |
          git config --global user.name 'Wayne Mao'
          git config --global user.email 'helloint@qq.com'
          git add ./data/*
          set +e
          git status | grep modified
          if [ $? -eq 0 ]
          then
              set -e
              git commit -am "Automated data process"
              git push
              exit 0
          else
              set -e
              echo "No changes since last run"
              exit 1
          fi
